#!/usr/bin/env bash
set -e

git submodule init
git submodule update

here="$(dirname "$0")"
here="$(cd "$here"; pwd)"

for file in "$here"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  if [[ !( "install readme fish-functions usr" =~ $name || -e ~/$dotname || -d $file/.git ) ]]; then
    ln -sfv ${file#$HOME/} "${HOME}/${dotname}"
  fi
done

for file in "$here"/usr/local/bin/*; do
  name="$(basename "$file" .md)"

  if [[ !(-e /usr/local/bin/$name) ]]; then
    ln -sfv ${file#$HOME/} "/usr/local/bin/${name}"
  fi
done
